version: "2.4"
services:

  wildfly:
    build: .
    image: hqli
    container_name: wildfly
    env_file:
      - .env
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    healthcheck:
      test: mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD}  -e 'use ${MYSQL_DATABASE};'
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
